baseURL = 'https://Diamond-Bluff.github.io/'
languageCode = 'en-us'
title = 'OPI Project Website'
theme = "ananke"

[params]
  post_content_classes = "sans-serif"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Diamond-Bluff"

[[params.ananke_socials]]
  name = "slack"
  url = "https://join.slack.com/t/opi-project/signup"
